services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    container_name: spring-boot-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/stormguard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - db

  db:
    image: postgres:alpine
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stormguard