spring:
  application:
    name: storm-guard
    description: API de gerenciamento de alertas de furacão

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    title: API StormGuard
    description: Documentação da API de gerenciamento de alertas de furacão
    version: OPENAPI_3_1

management:
  metrics:
    export:
      defaults:
        enabled: false
  endpoint:
    metrics:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info